name: firebase_notes
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  auto_route: ^5.0.4
  change_app_package_name: ^1.1.0
  cloud_firestore: ^4.1.0
  collection: ^1.16.0
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  hydrated_bloc: ^9.0.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  path_provider: ^2.0.11

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.0
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
