// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM6bq0iJPAL9KQOHMRFiJpNN6tPU5o2eo',
    appId: '1:874278160954:web:b624d990b59a2fcc364303',
    messagingSenderId: '874278160954',
    projectId: 'fourth-dimension-1',
    authDomain: 'fourth-dimension-1.firebaseapp.com',
    storageBucket: 'fourth-dimension-1.appspot.com',
    measurementId: 'G-R3SGJNF9FQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyRxaw0--VHhnT1bOpa10V3wPAeEWi9Z0',
    appId: '1:874278160954:android:c83f3d12edc648d2364303',
    messagingSenderId: '874278160954',
    projectId: 'fourth-dimension-1',
    storageBucket: 'fourth-dimension-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCeMhlum7TKS0JqnouyhnrUo22_Mr7asI',
    appId: '1:874278160954:ios:54489472690a5823364303',
    messagingSenderId: '874278160954',
    projectId: 'fourth-dimension-1',
    storageBucket: 'fourth-dimension-1.appspot.com',
    iosClientId: '874278160954-nc3tjl95pusrnqo8tlatmo0vb4li5vkd.apps.googleusercontent.com',
    iosBundleId: 'io.nftrecovery.fourthDimensionNetwork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCeMhlum7TKS0JqnouyhnrUo22_Mr7asI',
    appId: '1:874278160954:ios:04293dc6e7cd10a6364303',
    messagingSenderId: '874278160954',
    projectId: 'fourth-dimension-1',
    storageBucket: 'fourth-dimension-1.appspot.com',
    iosClientId: '874278160954-6vt0s5gom1f2s4pe33f5b92865tome6u.apps.googleusercontent.com',
    iosBundleId: 'com.provost-brent.fourthDimensionNetwork',
  );
}
